---
hero_image: images/about-me.png
theme: πορτοκαλί
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, σχεδιασμός-0, προγραμματισμός-1, phys-comp-0, κατασκευή-0, κοινότητα-0
title: Σχετικά με μένα
description: Χρησιμοποιήστε τη γλώσσα προγραμματισμού Python για προσομοιώσεις εικόνες με την χρήση γραμμάτων
original_url: https://codeclubprojects.org/en-GB/python/about-me
interests: ''
technologies: python
site_areas: έργα
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Εισαγωγή
  - 
    title: Τι θα χρειαστείτε
  - 
    title: Καλωσορίζω
  - 
    title: "Πρόκληση: Τι σκέφτεστε;"
  - 
    title: τέχνη ASCII
  - 
    title: "Πρόκληση: Για τον εαυτό σας"
  - 
    title: Το έτος 2025
  - 
    title: "Πρόκληση: Η ηλικία σας στα σκυλιά χρόνια"
  - 
    title: "Πρόκληση: Υπολογισμός κειμένου"
